### ISSUE TITLE
Missing input files for rule table_readme:

### ISSUE THREAD

**Issue by phil622** [hsigeman/findZX#1]
i meet this error,but i don't find a place to identity the file place. what can i do:

MissingInputException in line 139 of /public1/home/chenwy/app/findZX/workflow/rules/no_synteny_plotting.smk:
Missing input files for rule table_readme:
workflow/report/output_table_README.md

thanks

**Comment by hsigeman** [comment]
Hi! 

Sorry you are having problems. The file that is reported as missing (workflow/report/output_table_README.md) should be present at this location in the current version of findZX, so that is strange.. Would you mind updating findZX to the latest version (git pull) and try again? Do you see the missing file on your system?

Also, what is the command you are using to run the pipeline? If you are trying to analyze your own data, could you check first if the provided test dataset is working?

Thanks!
Hanna

**Comment by phil622** [comment]
I have figure it out. And i don't use the test dataset yet.
By the way, dose this pipeline has a offline model？or it have to connect to the website?

**Comment by hsigeman** [comment]
Ok, great that it works now!

The pipeline requires an internet connection to run, as many of the rules are from the "Snakemake Wrapper repository" (https://snakemake-wrappers.readthedocs.io/en/stable/). 

I will close this issue now, but let me know if you run into other problems.

Hanna
