### ISSUE TITLE
Missing input exception 

### ISSUE THREAD

**Issue by syd-alm** [hsigeman/findZX#16]
Hi Hanna,

I am having the same error as Suvi had (Issue #15) when using the pipeline on my own data:

`MissingInputException in line 167 of tools/findZX/workflow/rules/no_synteny_plotting.smk:
Missing input files for rule table_readme:
workflow/report/output_table_README.md
`

I also saw that another user also had this same issue (closed issue #1 ), but neither threads specified how the error was resolved. Any input or suggestions would be most appreciated!

I have successfully run the test dataset, and have checked that my config file has a path to the reference genome. I've attached my config file for reference.

Thank you in advance!
-Sydney

[p_herring_config.txt](https://github.com/hsigeman/findZX/files/13867551/p_herring_config.txt)

**Comment by hsigeman** [comment]
Hi Sydney, 

Issue #15 occurred because the command was not run from the `findZX` directory. Is it possible that you are also running it from a different location? It would be helpful if you could specify the command you are using to run the analysis. 

The configuration file looks fine, and if the test run finished successfully there shouldn't be any problems with the software either. 

Hanna

**Comment by syd-alm** [comment]
Hi Hanna, 

Yes, I was not running it from the findZX directory. Running the command from within the findZX directory resolved the issue. 

Thank you for the help and response! Much appreciated. 

Sydney
